### ISSUE TITLE
Better Startup Script

### ISSUE THREAD

**Issue by wunder957** [hitsz-ids/duetector#58]
We currently provide a very early [startup script](https://github.com/hitsz-ids/duetector/blob/main/docker/start.sh), which I hope will have the following functionality

- Pass parameters for `duectl-daemon start`
- Pass parameters for `duectl-server-daemon start`
- Provide a user-defined script entry point to replace the current user application (`JupyterLab`), mostly `exec` one script, which can be defined by the environment variable

**Comment by kayo09** [comment]
can i please be assigned to this issue?

**Comment by wunder957** [comment]
@kayo09 Hello and thank you for your interest in helping our project.

I've assigned this issue to you. Please fork this repository and submit your contribution as a PR to the `feature-startscript` branch, and I'll help you with Code Review and any other things.

If you have any questions, please leave a comment under this issue or just @ me.

Looking forward to your first PR! Thanks.

**Comment by wunder957** [comment]
This task is outdated and we will be redesigning the related functionality in 0.2.0
